version: '3.8'

services:
  app:
    build:
      context: final_project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  test:
    build:
      context: final_project
      dockerfile: Dockerfile
    depends_on:
      - app
    command: >
      sh -c "sleep 5 && pytest test.py --disable-warnings -v"
